name: generate-spec

on: pull_request

jobs:
  build_documents:
    name: build momentum netCDF document from source
    runs-on: ubuntu-latest
    steps:
    # Check out PR
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt -yq install asciidoctor ruby-asciidoctor-pdf ruby-asciidoctor-plantuml
    - name: build content
      run: |
        export apath=./specifications/momentum
        export ADOC=$apath/Momentum-netCDF
        asciidoctor --base-dir=$apath $ADOC.adoc
        asciidoctor-pdf --base-dir=$apath $ADOC.adoc
        cp $ADOC.pdf $apath/publish
        cp $ADOC.html $apath/publish
        ls -l $apath/publish
    # Upload artifact containing Momentum-netCDF
    - name: Upload cf-conventions doc preview
      uses: actions/upload-artifact@v2
      with:
        name: Momentum-netCDF
        path: ./specifications/momentum/publish/Momentum-netCDF.*
