name: generate-spec

on: pull_request

jobs:
  build_documents:
    name: build momentum netCDF document from source
    runs-on: ubuntu-latest
    steps:
    # Check out PR
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt -yq install texlive texlive-latex-extra inkscape
    - name: build content
      run: |
        export apath=./specifications/momentum
        export TEX=$apath/Momentum-netCDF
        TEXINPUTS=$apath/: pdflatex -shell-escape -halt-on-error -interaction=nonstopmode -output-directory=$apath $TEX
        TEXINPUTS=$apath/: BIBINPUTS=$apath/: bibtex $TEX
        TEXINPUTS=$apath/: pdflatex -output-directory=$apath -shell-escape $TEX
        TEXINPUTS=$apath/: pdflatex -output-directory=$apath -shell-escape $TEX
        cp $TEX.pdf $apath/publish
        ls -l $apath/publish
    # Upload artifact containing Momentum-netCDF.pdf
    - name: Upload cf-conventions doc preview
      uses: actions/upload-artifact@v2
      with:
        name: Momentum-netCDF
        path: ./specifications/momentum/publish/Momentum-netCDF.pdf
