name: commitSpecs

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }} 
      - name: Install dependencies
        run: |
          echo "dependencies"
      - name: Generate content and commit PR branch
        if: github.event.repository.fork == false
        run: |
          date > thisdate
          git add thisdate
          if [ -z "$(git status --porcelain)" ]; 
              then echo 'nothing to commit'
          else 
              git config --global user.email "${{ github.actor }}@users.noreply.github.com"
              git config --global user.name "${{ github.actor }}"
              git commit -am 'Github Action Commit'
              git push origin HEAD:${{ github.head_ref }}
          fi
